require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - test/dummy/**/*
    - coverage/**/*
    - lib/generators/**/templates/*

Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 15
Metrics/BlockLength:
  Exclude:
    - test/**/*
Style/GuardClause:
  Enabled: false
Style/StringLiterals:
  Enabled: false
