require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

AllCops:
  Exclude:
    - test/dummy/**/*
    - coverage/**/*
    - lib/generators/**/templates/*
    - vendor/bundle/**/*

Rails:
  Enabled: true
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 15
Metrics/BlockLength:
  Exclude:
    - test/**/*
Style/GuardClause:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
